name: Build

on: [push]

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller
                if (Test-Path requirements.txt) { pip install -r requirements.txt }
            - name: Build
              run: pyinstaller --onefile server.py
            - name: Delete old Windows artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                name: windows-executable
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows-executable
                path: dist/server.exe
            - name: Build client.py
              run: pyinstaller --onefile client.py
            - name: Upload client.py artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows-executable
                path: dist/client.exe
            - name: Build createsert.py
              run: pyinstaller --onefile createsert.py
            - name: Upload createsert.py artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows-executable
                path: dist/createsert.exe
            - name: Upload test DB
              uses: actions/upload-artifact@v4
              with:
                name: sqllite db
                path: app_database.db

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Build Server
              run: pyinstaller --onefile server.py
            - name: Delete old Linux artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                name: linux-executable
            - name: Upload Server artifact
              uses: actions/upload-artifact@v4
              with:
                name: linux-executable
                path: dist/server
            - name: Build Client
              run: pyinstaller --onefile client.py
            - name: Upload Client artifact
              uses: actions/upload-artifact@v4
              with:
                name: linux-executable
                path: dist/client
            - name: Build Createsert
              run: pyinstaller --onefile createsert.py
            - name: Upload createsert artifact
              uses: actions/upload-artifact@v4
              with:
                name: linux-executable
                path: dist/createsert        

    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Build
              run: pyinstaller --onefile server.py
            - name: Delete old macos artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                name: macos-executable
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: macos-executable
                path: dist/server
            - name: Build Client
              run: pyinstaller --onefile client.py
            - name: Upload Client artifact
              uses: actions/upload-artifact@v4
              with:
                name: macos-executable
                path: dist/client
            - name: Build Createsert
              run: pyinstaller --onefile createsert.py
            - name: Upload createsert artifact
              uses: actions/upload-artifact@v4
              with:
                name: macos-executable
                path: dist/createsert        
  